version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4
  allow-parallel-runners: true

linters:
  default: standard
  enable:
    # Style
    - revive
    - misspell
    - asciicheck
    - bidichk
    - usestdlibvars

    # Complexity & Dups
    - gocyclo
    - funlen
    - nestif
    - dupl

    # Just to be safe
    - gosec
    - staticcheck
    - gocritic
    - unused
    - bodyclose
    - errcheck
    - unparam
    - prealloc
    - nilerr
    - errorlint

  disable:
    - wsl

  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 3
  uniq-by-line: false
  new: true

output:
  formats:
    text:
      print-issued-lines: true
      colors: true
